### ISSUE TITLE
Start project

### ISSUE THREAD

**Issue by hkevman** [xg590/SX1276#11]
Hello,

I have like material : 

- 3 card ESP32  wrover dev 
- 3 DFROBOT Firebeetle Covers - LoRa 867Mhz SX1276
- Sensors
- 2 Grove lora 868Mhz seeed SX1276
- 1 Gateway Indoor ( The things network gateway)

And i wish to know if the matérial are compatible with your solution to work with Micropython to create a LoRaWan Network

**Comment by xg590** [comment]
> Hello,
> 
> I have like material :
> 
> * 3 card ESP32  wrover dev
> * 3 DFROBOT Firebeetle Covers - LoRa 867Mhz SX1276
> * Sensors
> * 2 Grove lora 868Mhz seeed SX1276
> * 1 Gateway Indoor ( The things network gateway)
> 
> And i wish to know if the matérial are compatible with your solution to work with Micropython to create a LoRaWan Network

LoRa is the fundamental technology here, working on the physical layer. This repo is a data link layer implementation. LoRaWan is another data link layer implementation (and so much more). So this repo should <b>NOT</b> be compatible with LoRaWan. 

I looked into Seeed Grove lora. It has a built-in MCU. You use AT commands to control the MCU so the interaction with LoRa is indirect. I believe the firmware is not compatible with LoRaWAN and any other LoRa devices (like your Firebeetle Covers). 

This repo is mainly for research/DIY purpose. I annotated the code extensively so you know how LoRa works and what every line does. Since you control everything, you can create a gateway for yourself (I guess SharathChandan (see #8 ) is trying to use this repo to make a gateway.)

If you are going to use this repo to make a LoRa (Not LoRaWAN) gateway.
* The SX1276 chip on DFROBOT Firebeetle Covers is operated through the SPI interface. It is good to use.
* I am not sure about your Gateway device.  May I have the purchase link?
